CREATE TABLE posts_test (LIKE posts INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES);

--;;

ALTER TABLE posts_test ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_test ON DELETE CASCADE;
